configured_endpoints: 14
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/epiphyte-corporation%2Fdoggyfi-sdk-39c69d728c19837f598bb0d8fcbe67540b638c89aca7cfebe32ea82c3c2ddcc8.yml
