configured_endpoints: 18
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/epiphyte-corporation%2Fdoggyfi-sdk-018a9b0ef545626b26c86ed46f835b6b53ad4ae0c64177483a5d30c3830f2f40.yml
