configured_endpoints: 11
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/epiphyte-corporation%2Fdoggyfi-sdk-30bf6d6044fdf8dd4536112c54dee2a29e924e3ac1dc70dd3571146b5cf4fdb6.yml
