configured_endpoints: 14
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/epiphyte-corporation%2Fdoggyfi-sdk-c2c711c6f9d051f1faf04838cd9cf3d875d26ffbbbc37c765c839b7501f32dea.yml
