configured_endpoints: 19
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/epiphyte-corporation%2Fdoggyfi-sdk-389c9c84b7866f79316e07fc04f51157c893a8e75cc374e650c514e6bea85ac8.yml
