configured_endpoints: 19
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/epiphyte-corporation%2Fdoggyfi-sdk-2f411ad3c3bfc97371fd9728ae730d0157e2e660c9824e767425d3256be68a10.yml
