name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - next

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    

    steps:
      - uses: actions/checkout@v4

      # - name: Set up Node
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: '18'

      # ➜ Install Bun
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 'latest'

      - name: Bootstrap
        run: ./scripts/bootstrap

      - name: Check types
        run: ./scripts/lint

  build:
    name: build
    runs-on: ubuntu-latest
    

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # ➜ Install Bun
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 'latest'

      # Now Bun is on PATH for the rest of the job
      - name: Bootstrap
        run: ./scripts/bootstrap

      - name: Check build
        run: ./scripts/build
  

  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # ➜ Install Bun
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 'latest'

      - name: Bootstrap
        run: ./scripts/bootstrap

      - name: Run tests
        run: ./scripts/test

